#!/usr/local/bin/python3

import sys
import os
import json
import gzip
import scsequtil.fastq as fq

script_name = os.path.split(__file__)[-1]


def main(indices_json, *fastqs):
    """extract reads corresponding to indices from passed fastq files

    output fastq files will be fastq.gz files

    :param str indices_json: json file containing array of indices to extract from fastq files
    :param [str] fastqs: list of fastq files from which records should be extracted
    :return [str]: list of filenames that were written
    """
    with open(indices_json, 'r') as f:
        indices = set(json.load(f))

    # create fastq readers
    readers = zip(fq.Reader(f) for f in fastqs)

    # create output filenames
    output_filenames = [f.partition('.fastq')[0] + '_subset.fastq.gz' for f in fastqs]

    # open output files
    output_fileobjs = [gzip.open(f, 'w') for f in output_filenames]

    # write records in indices to output files and close files
    try:
        for i, records in enumerate(readers):
            if i in indices:
                for record, fout in zip(records, output_fileobjs):
                    fout.write(record)

    finally:
        for f in output_fileobjs:
            f.close()

    return output_filenames


if __name__ == "__main__":
    if not len(sys.argv) == 4:  # print usage, exit
        print('Error: %s: Correct usage: %s indices.json fastq_1 ... fastq_n'
              % (script_name, script_name))
        sys.exit(2)
    else:  # process data, write filenames to stdout
        filenames = main(*sys.argv[1:])
        sys.stdout.write(' '.join(filenames))
