#!/usr/local/bin/python3

import os
import sys


def main(json_template, json_inputs):

    home = os.environ['HOME']
    with open(json_template, 'r') as f:
        data = f.read()
    data = data.replace('${HOME}', home)
    with open(json_inputs, 'w') as f:
        f.write(data)


if __name__ == "__main__":
    main(*sys.argv[1:])
