#' ---
#' title: HTML report Pipeline Quantification Summary
#' author: Jishu Xu
#' date: "`r format(Sys.time(), '%d %B, %Y')`"
#' output:
#'    html_document:
#'      toc: true
#'      highlight: tango
#'      theme: united
#'      fig_width: 8
#'      fig_height: 8
#' ---
#' 
#' # Purpose
#' In this section, we will compare and summary the quantification matrix by the following way
#'   *  set up threshold, for example TPM > 15 or CNT>10 as detectable
#'   *  set up threshold, for example, TPM <5 or CNT <5 as not-detectable
#'   *  compare two data matrix in term of their detectable and un-detectable genes. particulary those gene which are detectacble in 
#'   one but not detectacble in another
#'   *  summary those "inconsisttant genes" by gene biotype
#' 
#' # Input data
#' The key input data for this test are the data matrix generated by two pipelines, they can be gene counts matrix
#' or TPM, FPKM matrix. The detail of input data are listed below
#' 
#' * matrix1: data matrix from pipeline, such as base pipeline.
#' * matrix2: data matrix from pipeline, such as updated pipeline.
#' * gtf_file: gene annotation file in gtf format.
#' * metadata_file: meta information about cells, such as cell type. 
#' * output_prefix: output prefix or output name.
#' 
#' First load functions we will use in this test
source("analysis_functions.R")
#'
#' Here is the list of input parameters
option_list <- list(
  make_option(
    "--matrix1",
    type = "character",
    default = NULL,
    help = "data matrix file name",
    metavar = "character"
  ),
  make_option(
    "--matrix2",
    type = "character",
    default = NULL,
    help = "updated data matrix file name",
    metavar = "character"
  ),
  make_option(
    "--gtf_file",
    type = "character",
    default = NULL,
    help = "gtf annotation file",
    metavar = "character"
  ),
  make_option(
    "--groups",
    type = "character",
    default = NULL,
    help = "key id in meta data for t-test",
    metavar = "character"
  ),
  make_option(
    "--metadata_file",
    type = "character",
    default = NULL,
    help = "metadata file",
    metavar = "character"
  ),
  make_option(
    "--low_cut",
    type = "character",
    default = NULL,
    help = "low cutoff threshold",
    metavar = "character"
  ),
  make_option(
    "--high_cut",
    type = "character",
    default = NULL,
    help = "high cutoff threshold",
    metavar = "character"
  ),
  make_option(
    "--output_prefix",
    type = "character",
    default = NULL,
    help = "output prefix",
    metavar = "character"
  )
)
args<-strsplit(commandArgs(trailingOnly = TRUE),split=' ')
opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser,args=args[[1]])
matrixfile1 <- opt$matrix1
matrixfile2 <- opt$matrix2
gtf_file <-  opt$gtf_file
locut<-opt$low_cut
hicut<-opt$high_cut
output_name <- opt$output_prefix
#'
#' # Parse Inputs
#' 
#' ## Load Data Matrix
#' 
#' Data matrix files are *.csv file and can be count, TPM or FPKM matrix. 
#' For benchmarking purpose, TPM would be optimal choice.
# load matrix file 
mat1 <- read.csv(matrixfile1)
mat2 <- read.csv(matrixfile2)
rownames(mat1)<-mat1[,1]
rownames(mat2)<-mat2[,1]
# transfor matrix to 1/0 values based on threshold
mat1.d <- digitalizeMat(mat1[,-c(1:2)],locut,hicut)
mat2.d <- digitalizeMat(mat2[,-c(1:2)],locut,hicut)

#'  match matrix by header
colnames(mat1.d)<-colnames(mat1[,-c(1:2)])
colnames(mat2.d)<-colnames(mat2[,-c(1:2)])
rownames(mat1.d)<-rownames(mat1)
rownames(mat2.d)<-rownames(mat2)
mlist<-match(colnames(mat1.d),colnames(mat2.d))
mat2.d<-mat2.d[,mlist]
##'  Load gene annotation
genes <- ParseGene(gtf_file)
#' # Discrepency between two data matrix
#' Here we simply do subtraction between two matrix and will look for the subtraction equal to 2 or equal to  -2
dsub<-mat1.d -  mat2.d
sumb1<-SummaryQuantificationByType(dsub,genes,2)
sumb2<-SummaryQuantificationByType(dsub,genes,-2)
sumb1.m<-apply(sumb1[,-1],1,median)
sumb2.m<-apply(sumb2[,-1],1,median)
tot<-cbind(sumb1.m,-1*sumb2.m)
rownames(tot)<-sumb1$biotype
tot.sub<-subset(tot,tot[,1]>0 & tot[,2]<0)
colnames(tot.sub)<-c(paste("Base > ",hicut," & Updated <",locut,sep=""),paste("Base < ",locut," & Updated >",hicut,sep=""))
mtb<-melt(tot.sub)
pb <- ggbarplot(
  mtb,
  x = 'Var1',
  y = 'value',
  color = "Var2",
  fill = "Var2",
  # change fill color by FC
  x.text.angle = 90,
  # Rotate vertically x axis texts
  xlab = "median # Of Inconsistent Genes Per Cell",
  ylab = "",
  rotate = TRUE,
  caption = "Barplot: per cell, median of # genes are not consistently quantified between piplines",
  ggtheme = theme_minimal(),
  palette = "jco",
  legend.title = "Inconsistent Genes",
  legend = "top"
) + border()
pb
